### ISSUE TITLE
The new RecoverGeometryColumn breaks alembic migrations

### ISSUE THREAD

**Issue by caspervdw** [geoalchemy/geoalchemy2#372] opened 2022-03-09 09:48 UTC
Hi, GeoAlchemy2 developers,

I have a project that makes use of GeoAlchemy2 and alembic. Starting from GeoAlchemy2 0.11 (my guess is: #354) we have issues in running the alembic migrations in "batch" mode on a spatialite file. In short, a batch migration creates a temporary table with a new schema, then moves the data over, drops the old table, and renames the temporary table. This because sqlite does not allow for schema changes.

In version 0.10 we get the following queries, which work:

```
CREATE TABLE _alembic_tmp_v2_culvert (
        (...)
        the_geom NUMERIC DEFAULT ('') NOT NULL, 
        id INTEGER, 
        PRIMARY KEY (id)
)
INSERT INTO _alembic_tmp_v2_culvert (id, the_geom, ...) SELECT v2_culvert.id, v2_culvert.the_geom FROM v2_culvert
DROP TABLE v2_culvert
ALTER TABLE _alembic_tmp_v2_culvert RENAME TO v2_culvert
```

Because the geometry_columns where not touched in this process, everything still works out fine.

However in version 0.11 we get the following:

```
CREATE TABLE _alembic_tmp_v2_culvert (
        (...)
        the_geom GEOMETRY DEFAULT (''), 
        id INTEGER, 
        PRIMARY KEY (id)
)
SELECT RecoverGeometryColumn(?, ?, ?, ?, ?) AS "RecoverGeometryColumn_1"  % ('_alembic_tmp_v2_culvert', 'the_geom', -1, 'GEOMETRY', 2)
SELECT CreateSpatialIndex(?, ?) AS "CreateSpatialIndex_1" % ('_alembic_tmp_v2_culvert', 'the_geom')
INSERT INTO _alembic_tmp_v2_culvert (id, the_geom, ...) SELECT v2_culvert.id, v2_culvert.the_geom FROM v2_culvert
## ERROR sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: _alembic_tmp_v2_culvert
```

Also, the RecoverGeometryColumn returns `0` which means the operation failed.
The latest query raises a `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: _alembic_tmp_v2_culvert`

Is there an option to opt out from the RecoverGeometryColumn / CreateSpatialIndex calls?

**Comment by adrien-berchet** [comment] 2022-03-09 10:18
Hi @caspervdw 

Thanks for your report and sorry for this bug.
Could you provide a complete example that I can test locally please?
From the queries you posted here, I don't understand why the table would not exist?

For now there is no option to disable this `RecoverGeometryColumn` behavior but we could think about it. For the spatial index you can disable it with `Geometry(..., spatial_index=False)`.

**Comment by caspervdw** [comment] 2022-03-10 09:02
Hi, @adrien-berchet 

Thanks for your reply. I tried making a reproducable example but after 2 hours of hitting other issues I am giving up. Sorry I just don't have the time to delve into this further. One way to reproduce for you is cloning https://github.com/nens/threedi-modelchecker and then run the unittests with GeoAlchemy2 0.11. The failure should pop up.

**Comment by adrien-berchet** [comment] 2022-03-10 10:28
Ok, no problem, I will try to get what's happening with the tests of your repo.

**Comment by benoit9126** [comment] 2022-03-11 13:26
Hi, 

In the same context (`spatialite` migrations in batch mode, version 0.11), I had an error with the spatial index management:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) there is already a table named idx_table_geometry
[SQL: CREATE INDEX idx_table_geometry ON table (geometry)]
```

Installing the version 0.10.2 solved the problem as proposed by @caspervdw

**Comment by adrien-berchet** [comment] 2022-03-14 16:49
Hi @benoit9126 , thanks for the confirmation. Do you have an example or a test that shows this failure so I can test my working on branch on it?

I worked a bit on it and after some tests it seems that this issue is not directly caused by `RecoverGeometryColumn` but by the reflection process. In https://github.com/geoalchemy/geoalchemy2/commit/2bf9e1e2bf765dc41b81a45cd1f074426f886e95 I added types for spatial column reflection with SQLite dialect. But adding these types was not enough and the reflected types have wrong properties, so when Alembic creates the temporary table from the reflected one, it creates spatial columns with a generic `GEOMETRY` type instead of `POINT`, `LINESTRING` or whatever. So when one wants to insert a new element it fails because the triggers does not consider that `Geometry` is equal to `POINT`. While in `geoalchemy2 < 0.11`, the reflected spatial columns actually had a `NUMERICAL` type so there was no constraint on them and it was just working. And for the spatial index it's more or less the same issue, reflected columns have `spatial_index` set to `True` by default so a spatial index is created automatically after the table (which was not the case with `geoalchemy2 < 0.11`) and then a new index with the same name is created, thus it fails.

I tried to fix all this in #374 but I'm not sure it's ready yet, I have some more tests to perform. If you have some time to test on your side it would be great.

**Comment by caspervdw** [comment] 2022-03-15 12:30
Thanks @adrien-berchet for your work on this. Testing with your branch, I see that now indeed `RecoverGeometryColumn` has the correct type (`LINESTRING`) and the `INSERT` after that also works.

However I now get stuck at the `CREATE INDEX idx_v2_culvert_the_geom ON v2_culvert (the_geom)`. It seems that with the `DROP TABLE v2_culvert`, the spatial index is not dropped automatically.

**Comment by adrien-berchet** [comment] 2022-05-31 10:27
Hi @caspervdw 
I worked on #374 and I think it should cover your use case (in the tests I handle create/drop spatial tables and add/alter/drop columns). Nevertheless, a few changes are needed. For now, only `Spatialite >= 5` is supported and you have to use specific operations (e.g. `op.drop_geospatial_table` instead of `op.drop_table`, etc.). Note that auto-generation should automatically use these new operations for spatial columns are detected. If you have some time to test the new branch it would be super nice (note that you need to use the main branch of `Alembic` as there was an bug there that was breaking spatial indexes). I updated the doc according to the new changes so you can see what you have to change.
Anyway, I will wait the new release of Alembic to merge this.

**Comment by caspervdw** [comment] 2022-06-04 18:27
Thanks for the update!

**Comment by adrien-berchet** [comment] 2022-07-25 08:00
Hi there,
I think this issue is fixed now but feel free to reopen if you still have any issue about this.

**Closed by adrien-berchet** 2022-07-25 08:00 UTC
