### ISSUE TITLE
Issue with PostGIS spatial index using 0.11

### ISSUE THREAD

**Issue by martinfleis** [geoalchemy/geoalchemy2#376] opened 2022-03-22 20:54 UTC
Hi,

we're getting some reports in the geopandas repository that updating geoalchemy2 to 0.11 breaks the ability to write GeoPandas GeoDataFrame to PostGIS. See https://github.com/geopandas/geopandas/issues/2375. I've noticed some discussion that may be related in #372 but that refers to SpatiaLite. 

I am not sure if this is an intended change of the behaviour but I am also not entirely sure what was the intended change as the PR that probably changed this (#344) has no description.

I am happy to fix that on geopandas side if you don't see it as a regression though I have to admit I am not fully sure how at this moment. We currently do not control spatial index on the database side in any way.

**Comment by adrien-berchet** [comment] 2022-03-23 14:05
Hi @martinfleis 
Thank you for this report, I can reproduce this behavior. I had a quick look and I think it is due to the call to `Table.to_metadata()`, which actually calls again the `after_parent_attach` event and thus duplicates the index in the table object. I will think about a fix for this but I don't have much time at the moment.

**Closed** 2022-06-02 08:57 UTC

**Comment by adrien-berchet** [comment] 2022-06-16 21:50
Hi @blrichards 
The [GeoAlchemy2==0.12.1](https://pypi.org/project/GeoAlchemy2/0.12.1/) release is supposed to fix this issue, did you try it?

**Comment by thormme** [comment] 2024-04-16 16:56
This issue is still present as of geoalchemy2 `0.14.7`
I ran into the error while attempting to create a new spatial index on a geometry column using alembic.
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "idx_map_views_boundary" already exists

[SQL: CREATE INDEX idx_map_views_boundary ON map_views USING gist (boundary)]
```

The relevant lines in the alembic change script:

```
op.create_table('map_views',
sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT'), nullable=True))

op.create_index('idx_map_views_boundary', 'map_views', ['boundary'], unique=False, postgresql_using='gist')
```

**Comment by adrien-berchet** [comment] 2024-04-16 20:06
Hi @thormme 
I'm not sure I understand your issue, isn't it expected that the spatial index is automatically created? If you don't want to create it automatically you can pass `spatial_index=False` to the `Geometry` constructor. If it's something else, could be more specific? Maybe create a minimal working example?

**Comment by thormme** [comment] 2024-04-16 23:34
You are quite correct, I was misunderstanding the semantics of the geometry column. If anything other than user error, this would be a bug in the Alembic change script autogeneration.
Thanks for your help!
