### ISSUE TITLE
Using the <-> Operator

### ISSUE THREAD

**Issue by krak3n** [geoalchemy/geoalchemy2#94] opened 2015-02-22 15:10 UTC
Hi

Im trying to generate this query in SQLAlchemy for performing fast distance ordering:

``` sql
SELECT ST_Transform(geom, 27700) <-> ST_Transform(ST_SetSRID(ST_MakePoint(-2.21335, 53.5628), 4326), 27700) AS distance
FROM foo
ORDER BY distance
LIMIT 10
```

So the code should be:

``` python
distance = (ST_Transform(Foo.geom, 27000).op('<->')(ST_Transform(func.ST_SetSRID(func.ST_MakePoint(-2.21335, 53.5628), 4326), 27700))).label('distance')
db.session.query(Foo).with_entities(distance).order_by(distance).limit(10)
```

However the generated SQL is:

``` sql
SELECT ST_AsBinary(ST_Transform(foo.geom, 27000) <-> ST_Transform(ST_SetSRID(ST_MakePoint(-2.21335, 53.5628), 4326), 27700)) AS distance
FROM foo 
ORDER BY distance
LIMIT 10
```

So it gets wrapped in `ST_AsBinary` which is incorrect and breaks the query.

Whats the best way to achieve the desired query?

Thanks,

Chris

**Comment by simlu** [comment] 2015-06-19 03:45
This an exact duplicate of https://github.com/geoalchemy/geoalchemy2/issues/93

I'm still using the solution I've posted there. Maybe just +1 there and we can close this issue as duplicate.

**Closed** 2016-10-31 21:54 UTC
